### PR TITLE
style: fix button background color when clicked in HomeBanner and Navbar

### LINKED ISSUE #125: Button colour does not change when clicked
## Description

image

When we click on any white background button through the UI (in above example, the login button) the background changes to black and remains black. This bug needs to be fixed for all buttons in the UI.

### PR DESCRIPTION
**Pull request by gl-cardillo**
## Description

Button colour still black once clicked.

### Changes

This issue was caused by the :focus pseudo-class. It was applied to change the border and text color but not the background color. To resolve this, I have added the background change to the :focus pseudo-class.

fixes #125

### CODE REVIEW

**Comment by dvjsharma** [comment]
Hey @gl-cardillo, the same button is used multiple times throughout the UI, could you please fix them all in the PR?

**Comment by gl-cardillo** [comment]
Hello @dvjsharma , I have fixed the background in all buttons that use focus:

**Review by dvjsharma — APPROVED** [review]

**Comment by dvjsharma** [comment]
Hi @gl-cardillo ,changes looks good. Please rebase with latest master to remove the redundant commits.

**Comment by dvjsharma** [comment]
image

I can still see commits form other authors. Please rebase and force push.

**Pull request merged**
