### PR TITLE
fixed the overall ui

### LINKED ISSUE #87: The website is getting horizontal bar. With that the animation doesn't look cool.
**Describe the bug**
So as I can see the home page of the website is getting horizontal bar, and the ui can be enhanced by adding animations and more.

**Steps To Reproduce**
1. Go to Home page
2. AN directly see the horizontal bar

**Expected behavior**
The bar should be removed and multiple animations can be done.

**Screenshots**
image

I want to work on this issue under gssoc24. Just add a level2 label to it.

### PR DESCRIPTION
**Pull request by mohit-bhandari45**
Fixes #87

## Description
This pr fixes the issure #87. There was horizontal bar in the website which was very bad. I changed it by checking every page and finally founding out the error.

### Changes
I have changed the width property of the carousel, so that it never overflows. Plus I added animations to the websites.

### Screenshots
image

### CODE REVIEW

**Comment by sharmavikas4** [comment]
@dvjsharma i have reviewed the changes and it looks ok to me. You can check on your end before merging the request

**Comment by mohit-bhandari45** [comment]
@dvjsharma Please review this pr

**Comment by ShashankShekhar07** [comment]
LGTM!

**Comment by mohit-bhandari45** [comment]
hey bro, you forgot to add gssoc label to it. Please do it.

**Pull request merged**
