### PR TITLE
fix: Customize Page Form Submission Authentication and User Tracking   issue: #153

### PR DESCRIPTION
**Pull request by kaali001**
## Description

This PR addresses the issue of form submissions on the Customize page being allowed without user authentication and the absence of user information in the submitted data. The changes ensure that only authenticated users can submit the form, and the user information is included in the data sent to the server for better tracking and communication.

### Changes

1. Client Side :

 - Modified the form to include shoeModel and shoeSize data.
 - Ensured the form submission requires user authentication by checking for user data in the state.
 - Included user information in the data sent to the server for tracking purposes.

2. Server Side :

 - Updated the createcustomproduct controller to handle additional fields shoeModel and shoeSize.
 - Ensured that the user information is included and stored in the database.

3. Database Schema :

 - Updated the Design model to include a userId field and establish a relation with the Mainuser model for tracking user information.

### Checklist:

- [X]  User authentication added to Customize page form submission.
- [X]  Updated Customize page form to include shoeModel and shoeSize.
- [X]  Updated server to handle new data fields and ensure authentication.
- [x]  Updated Prisma schema to map Design with Mainuser.

### CODE REVIEW

**Comment by dvjsharma** [comment]
Hey @kaali001, I see a conflict in prisma schema file, PTAL and rebase.

**Comment by kaali001** [comment]
> Hey @kaali001, I see a conflict in prisma schema file, PTAL and rebase.

made the changes, now merge this PR. 
And please make sure to review PRs and merge ASAP.

**Comment by dvjsharma** [comment]
> > Hey @kaali001, I see a conflict in prisma schema file, PTAL and rebase.
> 
> made the changes, now merge this PR. And please make sure to review PRs and merge ASAP.

I hope you get that open source projects take time. General waiting period is 1 week

**Review by dvjsharma — APPROVED** [review]
Changes looks good. Working as expected

**Pull request merged**
