### PR TITLE
updated README, LEARN, CODE_OF_CONDUCT  files

### PR DESCRIPTION
**Pull request by kanikaa-3018**
i have included some features in the readme files as part of description of the website, these improvements will improve the user experience as well make the website more popular among the users. The important options like payment history as well as the mode are necessary for customer satisfaction. Also, the website allows a great oppurtunity to users i.e to design and modify the shoes they want to wear.

### CODE REVIEW

**Comment by ShashankShekhar07** [comment]
Hey @kanikaa-3018 please correct the name of website in all the markdown files and you do not need to change the git clone line

**Comment by dvjsharma** [comment]
Hey @kanikaa-3018, any updates?

**Comment by kanikaa-3018** [comment]
yes sir, ill upload the updated file tomorrow with all corrections, sorry for delay

**Comment by kanikaa-3018** [comment]
sir, i have updated it, please check and inform if anything else is to changed. Thankyou:)

**Comment by dvjsharma** [comment]
Please squash the commits into one, as we currently have 6 commits for essentially the same thing.

**Comment by kanikaa-3018** [comment]
so shall i create a new pr and merge all commits?

**Comment by dvjsharma** [comment]
Hey @kanikaa-3018, This task is already solved by #38. Closing as completed. Please re-open if necessary.

**Pull request closed without merging**
