### PR TITLE
validation added in the login and customize file

### PR DESCRIPTION
**Pull request by siddxharth1**
I have added the validation on the login and customize files

### CODE REVIEW

**Comment by ShashankShekhar07** [comment]
@siddxharth1 Can you add different alert message for each missing field?

**Comment by siddxharth1** [comment]
Added different alert message for different missing field

**Comment by siddxharth1** [comment]
Hey Divij , could you  please add the level and gssoc tag as same it was in the issue because this pr isn't counted as gssoc contribution.
issue : #23

**Comment by siddxharth1** [comment]
Hey @dvjsharma @ShashankShekhar07, could you please add the level and gssoc tag as same it was in the issue because this pr isn't counted as gssoc contribution.
issue : https://github.com/dvjsharma/Drawn2Shoe/issues/23 - #23

**Pull request merged**
